info:
  build:
    artifact: bookstore
    name: bookstore
    description: Simple bookstore with admin console
  spring:
    profiles: ${spring.profiles.active:default}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  servlet:
    # double the image size limit here in order to allow the custom file validation to be triggered
    multipart:
      max-file-size: 256KB
      max-request-size: 256KB
  session:
    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      initialize-schema: always
      table-name: spring_session

server:
  servlet:
    session:
      timeout: 15m
      tracking-modes: COOKIE

management:
  endpoints:
    web:
      exposure:
        include: '*'

---

spring:
  profiles: development
  thymeleaf:
    cache: false

---

spring:
  profiles: production
  thymeleaf:
    cache: true

server:
  compression:
    enabled: true

logging:
  level:
    ROOT: WARN
    org.apache.http: WARN
    org.apache.http.headers: WARN
    com.bookstore.Application: INFO
