spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  servlet:
    # double the image size limit here in order to allow the custom file validation to be triggered
    multipart:
      max-file-size: 256KB
      max-request-size: 256KB
  session:
    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      initialize-schema: always
      table-name: spring_session
  thymeleaf:
    cache: false

server:
  servlet:
    session:
      timeout: 15m
      tracking-modes: COOKIE

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: DEBUG
        type.descriptor.sql.BasicBinder: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
